apiVersion: 1

datasources:
  - name: OpenSearch-Logs
    type: grafana-opensearch-datasource
    uid: opensearch-logs
    access: proxy
    url: http://opensearch:9200
    editable: true
    jsonData:
      database: "ss4o_logs-otel-application-example"
      flavor: opensearch
      version: "2.19.0"
      timeField: "@timestamp"
      logMessageField: body
      logLevelField: severity.text
      maxConcurrentShardRequests: 5
