apiVersion: 1

datasources:
  - name: OpenSearch-Traces
    type: grafana-opensearch-datasource
    uid: opensearch-traces
    access: proxy
    url: http://opensearch:9200
    editable: true
    jsonData:
      database: "ss4o_traces-otel-aplicacao-example"
      flavor: opensearch
      version: "2.19.0"
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
