apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: opensearch-logs
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: PBFA97CFB590B2093
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: opensearch-logs
